### ISSUE TITLE
THANK YOU for the support!!

### ISSUE THREAD

**Issue by PySimpleGUI** [eagleEggs/ATFIEM#1]
I was looking through the screenshots last week and saw all the amazing stuff you were going SO VERY early in the history of PySimpleGUI.  You helped it get to where it is today.  You've also been sponsoring the project for over a year on GitHub.  I really appreciate all the support you've given.  It's nice to have great long-term users.  I hope you're doing well!  And still being as innovative as always.

**Comment by eagleEggs** [comment]
Hey Mike I hope you're doing well also! Thanks for the kind words. PSG is awesome, I use it for every project - and I love being able to pay it back through sponsorship on Github :) Those days were a lot of fun in the beginning and its really reached a completely stable place feature wise (Honestly was very stable from the start!). I still watch the updates come in all the time. Can't wait to see what updates are to come in the future.

**Comment by PySimpleGUI** [comment]
I feel bad about the rough-patch.  I'm in a MUCH better place now mentally.  Thank you for being so understanding and hanging in there and being supportive.  I **really** value the contribution you made in helping to make PySimpleGUI what it is.

**Comment by eagleEggs** [comment]
Of course, no worries! I'm sure we were both enduring many late nights with very little sleep haha. I'm also really glad we were able to talk it out and move forward, that's the best outcome for any type of conflict. Also great to hear things are going well with everything, it's been a strange year (almost two now), but the code always brings people back together :)

**Comment by PySimpleGUI** [comment]
> the code always brings people back together :)

![image](https://user-images.githubusercontent.com/46163555/141510264-9428d350-6a20-4e63-9dd7-c0d800f6886a.png)

It does!  Nothing like a shared goal.
